universe 		= docker
docker_image 		= pytorch/pytorch:latest
executable              = main.py
output                  = psl_out.$(ClusterId).$(ProcId).ckpt
error                   = psl_out.$(ClusterId).$(ProcId).err
log                     = psl_out.$(ClusterId).log
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
request_GPUs = 1
request_CPUs = 1
request_memory = 4G
requirements = UidDomain == "cs.uni-saarland.de"
+WantGPUHomeMounted = true
queue 1
